import Stripe from 'stripe';

export const stripePaymentMethods: Stripe.Checkout.SessionCreateParams.PaymentMethodType[] =
  [
    'card',
    'acss_debit',
    'affirm',
    'afterpay_clearpay',
    'alipay',
    'au_becs_debit',
    'bacs_debit',
    'bancontact',
    'blik',
    'boleto',
    'cashapp',
    'eps',
    'fpx',
    'giropay',
    'grabpay',
    'ideal',
    'klarna',
    'konbini',
    'link',
    'oxxo',
    'p24',
    'paynow',
    'paypal',
    'pix',
    'promptpay',
    'revolut_pay',
    'sepa_debit',
    'sofort',
    'swish',
    'us_bank_account',
    'wechat_pay',
    'zip',
    'acss_debit',
  ];
